# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    serializer:
        enable_annotations: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        default_context:
            enable_max_depth: true
            yaml_indentation: 2



    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.

    #esi: true
    #fragments: true
    php_errors:
        log: true

    # trusted_proxies: '0.0.0.0/0'
    # trusted_headers: ['x-forwarded-proto']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
