lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    # key under which the user identity will be stored in the token payload
    user_identity_field: username

    # token encoding/decoding settings
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        crypto_engine: openssl
        signature_algorithm: RS256

    # token extraction settings
    token_extractors:
        authorization_header: # look for a token as Authorization Header
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie: # check token in a cookie
            enabled: false
            name: BEARER
        query_parameter: # check token in query string parameter
            enabled: false
            name: bearer