nelmio_api_doc:
#  models:
#    use_jms: true
  documentation:
    # host: api.play4good.co
    # schemes: [http, https]
    info:
      title: API Documentation
      description: Gamer workplace
      version: 0.0.7
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas: # to filter documented areas
    default:
      path_patterns: [ ^/(?!_) ]
